import Head from "next/head";
import styles from '@/styles/Home.module.css'
import { Inter } from 'next/font/google'
import { NavBar } from "@/components/NavBar/intex";
import { cookies } from "next/headers";

const inter = Inter({ subsets: ['latin'] })

export default function Layout({children}){

	return (
		<>
		  <Head>
			<title>Araba Takip</title>
			<meta name="description" content="Generated by create next app" />
			<meta name="viewport" content="width=device-width, initial-scale=1" />
			<link rel="icon" href="/favicon.ico" />
		  </Head>
		  <main className="container mx-auto">
			<NavBar/>
			{children}
		  </main>
		  <div className="bg-gray-500 flex flex-row">
			
		  </div>
		</>
	  )
	
}